version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres


  postgres:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - CreateDB.sql/docker-entrypoint-initdb.d/

volumes:
  web_packages:
    driver: local
