version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: flask_app


  mysql:
    image: mysql:8.0
    volumes:
      - mysql-flask-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flask_app

volumes:
  mysql-flask-data:
