"""Initial migration.

Revision ID: 954bec9971cb
Revises: 
Create Date: 2021-11-25 14:00:08.189242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954bec9971cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apiV2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiV2',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='apiV2_pkey')
    )
    op.drop_table('analysis')
    # ### end Alembic commands ###
