"""Initial migration.

Revision ID: e83dfbe3b3d9
Revises: 
Create Date: 2021-11-25 15:09:52.734325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83dfbe3b3d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiV2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apiV2')
    # ### end Alembic commands ###
